-- AlterEnum: add new BookingStatus values (must be committed before being used as default)
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'PENDING_REVIEW';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'DOCUMENTS_REQUIRED';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'UNDER_VERIFICATION';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'WAITING_FOR_PAYMENT';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'PAYMENT_RECEIVED';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'VISA_PROCESSING';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'FLIGHT_RESERVED';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'HOTEL_RESERVED';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'TRANSPORTATION_CONFIRMED';
ALTER TYPE "BookingStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
