export const SITE = {
  name: 'কাবার পথে',
  nameEn: 'Kaaba r Pothe',
  legalName: 'Kaaba r Pothe Travels',
  tagline: 'হজ্জ ও উমরাহ প্ল্যাটফর্ম',
  url: 'https://kaabarpothe.com',
  locale: 'bn_BD',
  description:
    'কাবার পথে — প্রিমিয়াম হজ্জ ও উমরাহ প্যাকেজ। সৌদি মন্ত্রণালয় কর্তৃক লাইসেন্সপ্রাপ্ত, আলেম পরিচালিত, ৫০,০০০+ হাজী দ্বারা বিশ্বস্ত।',
  shortDescription: 'বাংলাদেশ থেকে নিরাপদ, সাশ্রয়ী ও বরকতপূর্ণ হজ্জ ও উমরাহ যাত্রা।',
  keywords: [
    'কাবার পথে',
    'kaabarpothe',
    'হজ্জ ২০২৬',
    'উমরাহ ২০২৬',
    'হজ্জ প্যাকেজ',
    'উমরাহ প্যাকেজ',
    'হজ্জ এজেন্সি বাংলাদেশ',
    'উমরাহ এজেন্সি ঢাকা',
    'ইসলামিক ভ্রমণ',
    'সৌদি আরব',
    'মক্কা',
    'মদিনা',
    'হাজী',
    'বাংলাদেশ হজ্জ',
    'Hajj 2026',
    'Umrah 2026',
    'Hajj package Bangladesh',
    'Umrah package Dhaka',
  ],
  ogImage: '/og-image.jpg',
  ogImageAlt: 'কাবার পথে — হজ্জ ও উমরাহ প্ল্যাটফর্ম',
  twitterHandle: '@kaabarpothe',
  contact: {
    email: 'admin@kaabarpothe.com',
    phone: '+৮৮০ ১৪০১-৬৯৬৫২৫',
    phoneHref: '+8801401696525',
    whatsapp: '+8801401696525',
    whatsappUrl: 'https://wa.me/8801401696525',
    address: {
      line1: 'Dhanmondi 27, Level 7, Shaptak Square',
      line2: 'Plot 380, Road 27, Dhaka 1207, Bangladesh',
      street: 'Dhanmondi 27, Level 7, Shaptak Square, Plot 380, Road 27',
      city: 'Dhaka',
      region: 'Dhaka',
      postalCode: '1207',
      country: 'BD',
    },
  },
} as const
